StoreFront.UI/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.Controllers
{
    public class OrdersController : Controller
    {
        private WritersSupplyEntities db = new WritersSupplyEntities();

        // GET: Orders
        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Product);
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.Product_ID = new SelectList(db.Products, "ProductID", "ProductName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "C_First_Name,C_Last_Name,C_Address,C_City,C_State,C_Country,OrderID,CustomerID,Total,Product_ID")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Product_ID = new SelectList(db.Products, "ProductID", "ProductName", order.Product_ID);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.Product_ID = new SelectList(db.Products, "ProductID", "ProductName", order.Product_ID);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "C_First_Name,C_Last_Name,C_Address,C_City,C_State,C_Country,OrderID,CustomerID,Total,Product_ID")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Product_ID = new SelectList(db.Products, "ProductID", "ProductName", order.Product_ID);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using System.Drawing; //Image
using StoreFront.UI.MVC.Models;
using StoreFront.UI.Utilities;//Gives us access to the ImageService.cs
using StoreFront.UI.Models;

namespace StoreFront.UI.Controllers
{
    public class ProductsController : Controller
    {
        private WritersSupplyEntities db = new WritersSupplyEntities();


        public ActionResult Tablets()
        {
            List<Product> tablets = new List<Product>();

            var t = from products in db.Products.Include(p => p.Category).Include(p => p.Manufacturer)
                    where products.Category.CategoryID == 1
                    select products.ProductID;
            return View(tablets);
        }
        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Availability1).Include(p => p.Category).Include(p => p.Manufacturer);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        //}

        //public ActionResult Tablets()
        //{
        //var tabletName = from products in db.Products.Include(p => p.Category).Include(p => p.Manufacturer)
        //                 where products.Category.CategoryID == 1
        //                 select products.ProductName;

        //var tabletImg = from products in db.Products.Include(p => p.Category).Include(p => p.Manufacturer)
        //                where products.Category.CategoryID == 1
        //                select products.Image;



        //TODONE Add to Cart Functionality - Step 3
        [HttpPost]
        public ActionResult AddToCart(int qty, int productID)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = null;
            if (Session["cart"] != null)
            {
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            }
            else
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }

            Product product = db.Products.Where(p => p.ProductID == productID).FirstOrDefault();
            if (product == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                CartItemViewModel item = new CartItemViewModel(qty, product);
                if (shoppingCart.ContainsKey(product.ProductID))
                {
                    shoppingCart[product.ProductID].Qty += qty;
                }
                else
                {
                    shoppingCart.Add(product.ProductID, item);
                }
                Session["cart"] = shoppingCart;

                Session["confirm"] = $"'{product.ProductName}' (Quantity: {qty}) added to cart";
            }

            return RedirectToAction("Index", "ShoppingCart");
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.Availability = new SelectList(db.Availabilities, "AvailabilityID", "Status");
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            ViewBag.ManufacturerID = new SelectList(db.Manufacturers, "ManufacturerID", "ManufacturerName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,ManufacturerID,Price,Availability,Description,Image,Size,CategoryID,OS")] Product product, HttpPostedFileBase productImg)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                //TODONE File Upload
                string file = "NoImage.png";

                if (productImg != null)
                {
                    file = productImg.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (goodExts.Contains(ext))
                    {
                        if (productImg.ContentLength <= 4194304)
                        {
                            file = Guid.NewGuid() + ext;

                            #region Resize Image
                            string savePath = Server.MapPath("~/Content/img/");
                            Image convertedImage = Image.FromStream(productImg.InputStream);
                            int maxImageSize = 500;
                            int maxThumbSize = 100;
                            ImageService.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                            #endregion
                        }
                        product.Image = file;
                    }
                }
                #endregion
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Availability = new SelectList(db.Availabilities, "AvailabilityID", "Status", product.Availability);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.ManufacturerID = new SelectList(db.Manufacturers, "ManufacturerID", "ManufacturerName", product.ManufacturerID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.Availability = new SelectList(db.Availabilities, "AvailabilityID", "Status", product.Availability);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.ManufacturerID = new SelectList(db.Manufacturers, "ManufacturerID", "ManufacturerName", product.ManufacturerID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,ManufacturerID,Price,Availability,Description,Image,Size,CategoryID,OS")] Product product, HttpPostedFileBase productImg)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                //TODONE File Upload
                string file = "NoImage.png";
                if (productImg != null)
                {
                    file = productImg.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };
                    if (goodExts.Contains(ext))
                    {
                        if (productImg.ContentLength <= 4194304)
                        {
                            file = Guid.NewGuid() + ext;

                            #region Resize Image
                            string savePath = Server.MapPath("~/Content/img/");
                            Image convertedImage = Image.FromStream(productImg.InputStream);

                            int maxImageSize = 500;
                            int maxThumbSize = 100;

                            ImageService.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                            #endregion

                            if (product.Image != null && product.Image != "NoImage.png")
                            {
                                string path = Server.MapPath("~/Content/img/");
                                ImageService.Delete(path, product.Image);
                            }
                        }
                        product.Image = file;
                    }
                }
                #endregion
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Availability = new SelectList(db.Availabilities, "AvailabilityID", "Status", product.Availability);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.ManufacturerID = new SelectList(db.Manufacturers, "ManufacturerID", "ManufacturerName", product.ManufacturerID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5

StoreFront.UI/Views/Shared/CarouselPartial.cshtml
<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
        <!--First slide-->
        <div class="carousel-item active">
            <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">
                <!-- Mask & flexbox options-->
                <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
                    <!-- Content -->
                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4">
                            <strong>Learn Bootstrap 4 with MDB</strong>
                        </h1>
                        <p>
                            <strong>Best & free guide of responsive web design</strong>
                        </p>
                        <p class="mb-4 d-none d-md-block">
                            <strong>
                                The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                                written versions
                                available. Create your own, stunning website.
                            </strong>
                        </p>
                        <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">
                            Start
                            free tutorial
                            <i class="fas fa-graduation-cap ml-2"></i>
                        </a>
                    </div>
                    <!-- Content -->
                </div>
                <!-- Mask & flexbox options-->
            </div>
        </div>
        <!--/First slide-->
        <!--Second slide-->
        <div class="carousel-item">
            <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">
                <!-- Mask & flexbox options-->
                <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
                    <!-- Content -->
                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4">
                            <strong>Learn Bootstrap 4 with MDB</strong>
                        </h1>
                        <p>
                            <strong>Best & free guide of responsive web design</strong>
                        </p>
                        <p class="mb-4 d-none d-md-block">
                            <strong>
                                The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                                written versions
                                available. Create your own, stunning website.
                            </strong>
                        </p>
                        <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">
                            Start
                            free tutorial
                            <i class="fas fa-graduation-cap ml-2"></i>
                        </a>
                    </div>
                    <!-- Content -->
                </div>
                <!-- Mask & flexbox options-->
            </div>
        </div>
        <!--/Second slide-->
        <!--Third slide-->
        <div class="carousel-item">
            <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">
                <!-- Mask & flexbox options-->
                <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
                    <!-- Content -->
                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4">
                            <strong>Learn Bootstrap 4 with MDB</strong>
                        </h1>
                        <p>
                            <strong>Best & free guide of responsive web design</strong>
                        </p>
                        <p class="mb-4 d-none d-md-block">
                            <strong>
                                The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                                written versions
                                available. Create your own, stunning website.
                            </strong>
                        </p>
                        <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">
                            Start
                            free tutorial
                            <i class="fas fa-graduation-cap ml-2"></i>
                        </a>
                    </div>
                    <!-- Content -->
                </div>
                <!-- Mask & flexbox options-->
            </div>
        </div>
        <!--/Third slide-->
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->

StoreFront.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    @* AJAX *@
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.css">
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">
            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="@Url.Action("Index","Home")">
                <strong class="blue-text">Writer's Supply</strong>
            </a>
            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="@Url.Action("Index", "Home")">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    @*<li class="nav-item">
                            <a class="nav-link waves-effect" href="@Url.Action("index", "Products")">Products</a>
                        </li>*@
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("Index", "Products")">Products</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Categories")">Categories</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Manufacturers")">Manufacturers</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Orders")">Orders</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("Index", "Departments")">Departments</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Employees")">Employees</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "RolesAdmin")">Roles</a>
                            </div>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="@Url.Action("index", "ShoppingCart")" target="_blank">Checkout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="@Url.Action("Contact", "Home")">Contact</a>
                    </li>
                    @*<li class="nav-item">
                            <a class="nav-link waves-effect" href="@Url.Action("About", "Home")">About</a>
                        </li>

                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">About MDB</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
                                   target="_blank">Free download</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link waves-effect" href="https://mdbootstrap.com/education/bootstrap/" target="_blank">
                                    Free
                                    tutorials
                                </a>
                            </li>*@
                </ul>
                <!-- Right -->
                <ul class="navbar-nav nav-flex-icons">
                    <li class="nav-item">
                        @if (Session["cart"] != null && ((Dictionary<int, StoreFront.UI.Models.CartItemViewModel>)Session["cart"]).Count > 0)
                        {
                            <a href="@Url.Action("index", "ShoppingCart")" class="nav-link waves-effect" target="_blank">
                                @*<span class="badge red z-depth-1 mr-1"> 1 </span>*@
                                <i class="fas fa-shopping-cart"></i>
                                @{
                                    Dictionary<int, StoreFront.UI.Models.CartItemViewModel> cartItems = (Dictionary<int, StoreFront.UI.Models.CartItemViewModel>)Session["cart"];
                                    int items = 0; //running total variable

                                    foreach (var item in cartItems)
                                    {
                                        items += item.Value.Qty;
                                    }
                                    @items

                                }
                                @*<span class="clearfix d-none d-sm-inline-block"> Cart </span>*@
                            </a>
                        }
                        else
                        {
                            <a href="@Url.Action("index", "ShoppingCart")" class="nav-link waves-effect" target="_blank"><i class="fas fa-shopping-cart"></i></a>
                        }
                    </li>
                    @*
                        <li class="nav-item">
                            <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="nav-link border border-light rounded waves-effect"
                               target="_blank">
                                <i class="fab fa-github mr-2"></i>MDB GitHub
                            </a>
                        </li>*@
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <br clear="all">
    <!-- Carousel -->
    @if ((ViewBag.RenderCarousel != null) && ((bool)ViewBag.RenderCarousel))
    {
        @Html.Partial("_CarouselPartial")
    }
    <div class="container-fluid fixed-padding">@RenderBody()</div>

    <!--Footer-->

    <footer class="text-center font-small mt-4 wow fadeIn fixed-bottom" @*page-footer*@>
        <!--Call to action-->
        @*<div class="pt-4">
                <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
                   role="button">
                    Download MDB
                    <i class="fas fa-download ml-2"></i>
                </a>
                <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">
                    Start
                    free tutorial
                    <i class="fas fa-graduation-cap ml-2"></i>
                </a>
            </div>
            <!-- End Call to action-->
            <hr class="my-4">
            <!-- Social icons -->
            <div class="pb-4">
            Writer's Supply
            <a href="https://www.facebook.com/mdbootstrap" target="_blank">
                    <i class="fab fa-facebook-f mr-3"></i>
                </a>
                <a href="https://twitter.com/MDBootstrap" target="_blank">
                    <i class="fab fa-twitter mr-3"></i>
                </a>
                <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
                    <i class="fab fa-youtube mr-3"></i>
                </a>
                <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
                    <i class="fab fa-google-plus-g mr-3"></i>
                </a>
                <a href="https://dribbble.com/mdbootstrap" target="_blank">
                    <i class="fab fa-dribbble mr-3"></i>
                </a>
                <a href="https://pinterest.com/mdbootstrap" target="_blank">
                    <i class="fab fa-pinterest mr-3"></i>
                </a>
                <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
                    <i class="fab fa-github mr-3"></i>
                </a>
                <a href="http://codepen.io/mdbootstrap/" target="_blank">
                    <i class="fab fa-codepen mr-3"></i>
                </a>
            </div>*@
        <!-- End Social icons -->
        <!--Copyright-->
        <div @*class="footer-copyright py-3"*@>
            © @DateTime.Now.Year S. Tessa Toney
            @*<a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>*@
        </div>
        <!-- End Copyright-->
    </footer>
    <!-- End Footer-->

    <script src="https://unpkg.com/typewriter-effect@latest/dist/core.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @* The links below were added for our AJAX functionality *@
    <!--ADDEDjQuery UI CDN-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- ADDED jQuery Ajax CDN-->
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)


</body>
</html>